Algoritmo "EX2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/12/2024
Var
// Seção de Declarações das variáveis 
cont:inteiro
valor1,valor2: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-1

repita
escreval (cont)
cont <-cont +1
ate cont >10
Fimalgoritmo